version: '3.7'

services:
  backend:
    build: .
    container_name: "DRF"
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
    - "8000:8000"
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: 'postgres_db'
    volumes:
      - trading:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - .env

  broker:
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - backend

  worker:
    build: .
    container_name: "celery"
    command: "celery -A config worker -l info"
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - broker


volumes:
  trading:
    external: true
