# Generated by Django 4.2.3 on 2023-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradinguser',
            name='avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
