# Generated by Django 4.2.3 on 2023-07-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradinguser",
            name="balance",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
