# Generated by Django 4.2.3 on 2023-07-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_tradinguser_balance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tradinguser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveConstraint(
            model_name="tradinguser",
            name="balance_greater_or_equals_to_zero",
        ),
        migrations.AlterField(
            model_name="tradinguser",
            name="balance",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
