# Generated by Django 4.2.3 on 2023-07-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotion_avatar'),
        ('profiles', '0002_alter_tradinguser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradinguser',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradinguser',
            name='subscription',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='promotions.promotion'),
        ),
    ]
