# Generated by Django 4.2.3 on 2023-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_tradinguser_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tradinguser",
            options={},
        ),
        migrations.AddConstraint(
            model_name="tradinguser",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)),
                name="balance_greater_or_equals_to_zero",
            ),
        ),
    ]
