# Generated by Django 4.2.3 on 2023-07-14 21:48

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
        ("profiles", "0006_alter_tradinguser_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradinguser",
            name="role",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("admin", "admin"),
                    ("analyst", "analyst"),
                    ("default", "default"),
                ],
                default="admin",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="tradinguser",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="promotions.promotion",
            ),
        ),
    ]
