# Generated by Django 4.2.3 on 2023-07-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('profiles', '0009_alter_tradinguser_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradinguser',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='promotions.promotion'),
        ),
    ]
