# Generated by Django 4.2.3 on 2023-07-14 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
        ("profiles", "0010_alter_tradinguser_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradinguser",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="promotions.promotion",
            ),
        ),
    ]
