# Generated by Django 4.2.3 on 2023-07-17 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_alter_tradinguser_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradinguser",
            name="login",
        ),
    ]
