# Generated by Django 4.2.3 on 2023-07-29 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
        ("profiles", "0012_remove_tradinguser_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradinguser",
            name="subscription",
        ),
        migrations.CreateModel(
            name="PromotionUserSubscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tradinguser",
            name="subscription",
            field=models.ManyToManyField(
                null=True,
                through="profiles.PromotionUserSubscriptions",
                to="promotions.promotion",
            ),
        ),
    ]
