# Generated by Django 4.2.3 on 2023-07-29 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
        ("profiles", "0013_remove_tradinguser_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionusersubscriptions",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="promotions.promotion"
            ),
        ),
        migrations.AlterField(
            model_name="promotionusersubscriptions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tradinguser",
            name="subscription",
            field=models.ManyToManyField(
                through="profiles.PromotionUserSubscriptions", to="promotions.promotion"
            ),
        ),
    ]
