# Generated by Django 4.2.3 on 2023-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_alter_promotionusersubscriptions_promotion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradinguser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active."
                " Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
