# Generated by Django 4.2.3 on 2023-07-12 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0002_alter_promotion_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioUserPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='portfolio.portfolio')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='promotions.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='promotions',
            field=models.ManyToManyField(through='portfolio.PortfolioUserPromotion',
                                         to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
