# Generated by Django 4.2.3 on 2023-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='promotions',
            field=models.ManyToManyField(blank=True, null=True, through='portfolio.PortfolioUserPromotion', to='promotions.promotion'),
        ),
    ]
