# Generated by Django 4.2.3 on 2023-07-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
        ("portfolio", "0003_alter_portfolio_promotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="promotions",
            field=models.ManyToManyField(
                blank=True,
                through="portfolio.PortfolioUserPromotion",
                to="promotions.promotion",
            ),
        ),
    ]
