# Generated by Django 4.2.3 on 2023-07-11 15:26
from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[type] = []

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="promotions/avatar/"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("description", models.TextField(default="The most beneficial asset")),
            ],
        ),
    ]
