# Generated by Django 4.2.3 on 2023-07-13 10:21

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', django_enum.fields.EnumCharField(blank=True, choices=[('pending', 'pending'), ('completed successfully', 'completed successfully'), ('completed with an error', 'completed with an error')], max_length=23, null=True)),
                ('total_sum', models.DecimalField(decimal_places=10, max_digits=20)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotions.promotion')),
            ],
        ),
    ]
