# Generated by Django 4.2.3 on 2023-07-15 13:10

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="action",
            field=django_enum.fields.EnumCharField(
                choices=[("sale", "sale"), ("purchase", "purchase")],
                default="purchase",
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("pending", "pending"),
                    ("completed successfully", "completed successfully"),
                    ("completed with an error", "completed with an error"),
                ],
                default="pending",
                max_length=23,
            ),
        ),
    ]
