# Generated by Django 4.2.3 on 2023-08-03 11:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_ordered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordered_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 3, 10, 59, 58, 400102, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
