# Generated by Django 4.2.4 on 2023-08-06 12:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_order_ordered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordered_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 6, 12, 55, 21, 818647, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
