# Generated by Django 4.2.3 on 2023-07-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auto_orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="autoorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auto_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="autoorder",
            constraint=models.CheckConstraint(
                check=models.Q(("total_sum__gte", 0)),
                name="auto_order_total_sum_greater_or_equals_to_zero",
            ),
        ),
    ]
