# Generated by Django 4.2.3 on 2023-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoorder',
            name='direction',
            field=models.DecimalField(decimal_places=10, default=1.32, max_digits=20),
            preserve_default=False,
        ),
    ]
