# Generated by Django 4.2.3 on 2023-07-15 13:10

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auto_orders', '0004_autoorder_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoorder',
            name='action',
            field=django_enum.fields.EnumCharField(choices=[('sale', 'sale'), ('purchase', 'purchase')], default='purchase', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoorder',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('pending', 'pending'), ('completed successfully', 'completed successfully'), ('completed with an error', 'completed with an error')], default='pending', max_length=23),
        ),
    ]
