# Generated by Django 4.2.3 on 2023-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_orders", "0005_alter_autoorder_action_alter_autoorder_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autoorder",
            old_name="begun_at",
            new_name="closed_at",
        ),
        migrations.AlterField(
            model_name="autoorder",
            name="total_sum",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
