# Generated by Django 4.2.3 on 2023-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_orders", "0006_rename_begun_at_autoorder_closed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoorder",
            name="closed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
