# Generated by Django 4.2.3 on 2023-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_orders", "0007_alter_autoorder_closed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoorder",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
