# Generated by Django 4.2.3 on 2023-08-02 09:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_orders", "0009_alter_autoorder_promotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoorder",
            name="ordered_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 2, 9, 38, 17, 340731, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
